<a href="https://colab.research.google.com/github/Danishzaman-0786/Next_Word_Predictor/blob/main/NEXT_WORD_PRE%3E%3E.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [283]:
Data_ = """ About the Program
    What is the course fee for  Data Science Mentorship Program (DSMP 2023)
    The course follows a monthly subscription model where you have to make monthly payments of Rs 799/month.
    What is the total duration of the course?
    The total duration of the course is 7 months. So the total course fee becomes 799*7 = Rs 5600(approx.)
    What is the syllabus of the mentorship program?
    We will be covering the following modules:
    Python Fundamentals
    Python libraries for Data Science
    Data Analysis
    SQL for Data Science
    Maths for Machine Learning
    ML Algorithms
    Practical ML
    MLOPs
    Case studies
    You can check the detailed syllabus here - https://learnwith.campusx.in/courses/CampusX-Data-Science-Mentorship-Program-637339afe4b0615a1bbed390
    Will Deep Learning and NLP be a part of this program?
    No, NLP and Deep Learning both are not a part of this program’s curriculum.
    What if I miss a live session? Will I get a recording of the session?
    Yes all our sessions are recorded, so even if you miss a session you can go back and watch the recording.
    Where can I find the class schedule?
    Checkout this google sheet to see month by month time table of the course - https://docs.google.com/spreadsheets/d/16OoTax_A6ORAeCg4emgexhqqPv3noQPYKU7RJ6ArOzk/edit?usp=sharing.
    What is the time duration of all the live sessions?
    Roughly, all the sessions last 2 hours.
    What is the language spoken by the instructor during the sessions?
    Hinglish
    How will I be informed about the upcoming class?
    You will get a mail from our side before every paid session once you become a paid user.
    Can I do this course if I am from a non-tech background?
    Yes, absolutely.
    I am late, can I join the program in the middle?
    Absolutely, you can join the program anytime.
    If I join/pay in the middle, will I be able to see all the past lectures?
    Yes, once you make the payment you will be able to see all the past content in your dashboard.
    Where do I have to submit the task?
    You don’t have to submit the task. We will provide you with the solutions, you have to self evaluate the task yourself.
    Will we do case studies in the program?
    Yes.
    Where can we contact you?
    You can mail us at nitish.campusx@gmail.com
    Payment/Registration related questions
    Where do we have to make our payments? Your YouTube channel or website?
    You have to make all your monthly payments on our website. Here is the link for our website - https://learnwith.campusx.in/
    Can we pay the entire amount of Rs 5600 all at once?
    Unfortunately no, the program follows a monthly subscription model.
    What is the validity of monthly subscription? Suppose if I pay on 15th Jan, then do I have to pay again on 1st Feb or 15th Feb
    15th Feb. The validity period is 30 days from the day you make the payment. So essentially you can join anytime you don’t have to wait for a month to end.
    What if I don’t like the course after making the payment. What is the refund policy?
    You get a 7 days refund period from the day you have made the payment.
    I am living outside India and I am not able to make the payment on the website, what should I do?
    You have to contact us by sending a mail at nitish.campusx@gmail.com
    Post registration queries
    Till when can I view the paid videos on the website?
    This one is tricky, so read carefully. You can watch the videos till your subscription is valid. Suppose you have purchased subscription on 21st Jan, you will be able to watch all the past paid sessions in the period of 21st Jan to 20th Feb. But after 21st Feb you will have to purchase the subscription again.
    But once the course is over and you have paid us Rs 5600(or 7 installments of Rs 799) you will be able to watch the paid sessions till Aug 2024.
    Why lifetime validity is not provided?
    Because of the low course fee.
    Where can I reach out in case of a doubt after the session?
    You will have to fill a google form provided in your dashboard and our team will contact you for a 1 on 1 doubt clearance session
    If I join the program late, can I still ask past week doubts?
    Yes, just select past week doubt in the doubt clearance google form.
    I am living outside India and I am not able to make the payment on the website, what should I do?
    You have to contact us by sending a mail at nitish.campusx@gmai.com
    Certificate and Placement Assistance related queries
    What is the criteria to get the certificate?
    There are 2 criterias:
    You have to pay the entire fee of Rs 5600
    You have to attempt all the course assessments.
    I am joining late. How can I pay payment of the earlier months?
    You will get a link to pay fee of earlier months in your dashboard once you pay for the current month.
    I have read that Placement assistance is a part of this program. What comes under Placement assistance?
    This is to clarify that Placement assistance does not mean Placement guarantee. So we dont guarantee you any jobs or for that matter even interview calls. So if you are planning to join this course just for placements, I am afraid you will be disappointed. Here is what comes under placement assistance
    Portfolio Building sessions
    Soft skill sessions
    Sessions with industry mentors
    Discussion on Job hunting strategies
"""

In [284]:
import tensorflow as tf
from tensorflow.keras.preprocessing.text import Tokenizer


In [285]:
Tokenizer=Tokenizer()

In [286]:
Tokenizer.fit_on_texts([Data_])

In [287]:
(Tokenizer_.word_index)

{'the': 1,
 'you': 2,
 'i': 3,
 'to': 4,
 'a': 5,
 'of': 6,
 'is': 7,
 'have': 8,
 'will': 9,
 'can': 10,
 'what': 11,
 'course': 12,
 'program': 13,
 'in': 14,
 'for': 15,
 'all': 16,
 'sessions': 17,
 'on': 18,
 'be': 19,
 'and': 20,
 'this': 21,
 'if': 22,
 'am': 23,
 'pay': 24,
 'payment': 25,
 'make': 26,
 'we': 27,
 'do': 28,
 'subscription': 29,
 'where': 30,
 'rs': 31,
 'so': 32,
 'campusx': 33,
 'session': 34,
 'our': 35,
 'paid': 36,
 'join': 37,
 'able': 38,
 'your': 39,
 'website': 40,
 'placement': 41,
 'fee': 42,
 'data': 43,
 'monthly': 44,
 'month': 45,
 'not': 46,
 'get': 47,
 'yes': 48,
 'once': 49,
 'past': 50,
 'feb': 51,
 'assistance': 52,
 'science': 53,
 '7': 54,
 '5600': 55,
 'are': 56,
 'watch': 57,
 'google': 58,
 'by': 59,
 'com': 60,
 'mail': 61,
 'from': 62,
 'contact': 63,
 'us': 64,
 'at': 65,
 'or': 66,
 'doubt': 67,
 'mentorship': 68,
 'payments': 69,
 '799': 70,
 'total': 71,
 'duration': 72,
 'months': 73,
 'learning': 74,
 'case': 75,
 'here': 76,
 '

In [288]:
type(Data_)

str

In [289]:
#we need to split the senteses
for i in Data_.split('\n'):
  print(i)


 About the Program
    What is the course fee for  Data Science Mentorship Program (DSMP 2023)
    The course follows a monthly subscription model where you have to make monthly payments of Rs 799/month.
    What is the total duration of the course?
    The total duration of the course is 7 months. So the total course fee becomes 799*7 = Rs 5600(approx.)
    What is the syllabus of the mentorship program?
    We will be covering the following modules:
    Python Fundamentals
    Python libraries for Data Science
    Data Analysis
    SQL for Data Science
    Maths for Machine Learning
    ML Algorithms
    Practical ML
    MLOPs
    Case studies
    You can check the detailed syllabus here - https://learnwith.campusx.in/courses/CampusX-Data-Science-Mentorship-Program-637339afe4b0615a1bbed390
    Will Deep Learning and NLP be a part of this program?
    No, NLP and Deep Learning both are not a part of this program’s curriculum.
    What if I miss a live session? Will I get a recording o

In [290]:
#now we find the numbers format
input_data=[]
for i in Data_.split('\n'):
  p_=(Tokenizer.texts_to_sequences([i])[0])
  for i in range(1,len(p_)):
     input_data.append(p_[:i+1])

In [291]:
input_data

[[93, 1],
 [93, 1, 13],
 [11, 7],
 [11, 7, 1],
 [11, 7, 1, 12],
 [11, 7, 1, 12, 42],
 [11, 7, 1, 12, 42, 15],
 [11, 7, 1, 12, 42, 15, 43],
 [11, 7, 1, 12, 42, 15, 43, 53],
 [11, 7, 1, 12, 42, 15, 43, 53, 68],
 [11, 7, 1, 12, 42, 15, 43, 53, 68, 13],
 [11, 7, 1, 12, 42, 15, 43, 53, 68, 13, 147],
 [11, 7, 1, 12, 42, 15, 43, 53, 68, 13, 147, 148],
 [1, 12],
 [1, 12, 94],
 [1, 12, 94, 5],
 [1, 12, 94, 5, 44],
 [1, 12, 94, 5, 44, 29],
 [1, 12, 94, 5, 44, 29, 95],
 [1, 12, 94, 5, 44, 29, 95, 30],
 [1, 12, 94, 5, 44, 29, 95, 30, 2],
 [1, 12, 94, 5, 44, 29, 95, 30, 2, 8],
 [1, 12, 94, 5, 44, 29, 95, 30, 2, 8, 4],
 [1, 12, 94, 5, 44, 29, 95, 30, 2, 8, 4, 26],
 [1, 12, 94, 5, 44, 29, 95, 30, 2, 8, 4, 26, 44],
 [1, 12, 94, 5, 44, 29, 95, 30, 2, 8, 4, 26, 44, 69],
 [1, 12, 94, 5, 44, 29, 95, 30, 2, 8, 4, 26, 44, 69, 6],
 [1, 12, 94, 5, 44, 29, 95, 30, 2, 8, 4, 26, 44, 69, 6, 31],
 [1, 12, 94, 5, 44, 29, 95, 30, 2, 8, 4, 26, 44, 69, 6, 31, 70],
 [1, 12, 94, 5, 44, 29, 95, 30, 2, 8, 4, 26, 44, 69, 6

In [292]:
#how to find the maximum lenght of sentense
max_=max([len(i) for i in input_data])
max_

57

In [293]:
#maximum lenght_sentes=57
#we use the zero padding
from tensorflow.keras.preprocessing.sequence import pad_sequences
input_padding=pad_sequences(input_data,maxlen=max_,padding='pre')

In [294]:
input_padding

array([[  0,   0,   0, ...,   0,  93,   1],
       [  0,   0,   0, ...,  93,   1,  13],
       [  0,   0,   0, ...,   0,  11,   7],
       ...,
       [  0,   0,   0, ..., 279,  18, 280],
       [  0,   0,   0, ...,  18, 280, 281],
       [  0,   0,   0, ..., 280, 281, 282]], dtype=int32)

In [295]:
X=input_padding[:,:-1]
#we use another method



In [296]:
X

array([[  0,   0,   0, ...,   0,   0,  93],
       [  0,   0,   0, ...,   0,  93,   1],
       [  0,   0,   0, ...,   0,   0,  11],
       ...,
       [  0,   0,   0, ...,   0, 279,  18],
       [  0,   0,   0, ..., 279,  18, 280],
       [  0,   0,   0, ...,  18, 280, 281]], dtype=int32)

In [297]:
#as well as using for y
Y=input_padding[:,-1]

In [298]:
Y

array([  1,  13,   7,   1,  12,  42,  15,  43,  53,  68,  13, 147, 148,
        12,  94,   5,  44,  29,  95,  30,   2,   8,   4,  26,  44,  69,
         6,  31,  70,  45,   7,   1,  71,  72,   6,   1,  12,  71,  72,
         6,   1,  12,   7,  54,  73,  32,   1,  71,  12,  42, 149,  70,
        54,  31,  55, 150,   7,   1,  96,   6,   1,  68,  13,   9,  19,
       151,   1, 152, 153, 154, 155,  15,  43,  53, 156,  15,  43,  53,
        15, 159,  74, 160,  98,  99,  10, 163,   1, 164,  96,  76,  77,
       100,  33,  14, 165,  33,  43,  53,  68,  13, 166, 101,  74,  20,
       102,  19,   5,  78,   6,  21,  13, 102,  20, 101,  74, 167,  56,
        46,   5,  78,   6,  21, 168, 169,  22,   3, 104,   5, 105,  34,
         9,   3,  47,   5, 106,   6,   1,  34,  16,  35,  17,  56, 170,
        32, 107,  22,   2, 104,   5,  34,   2,  10, 171, 172,  20,  57,
         1, 106,  10,   3, 173,   1, 108, 174,  21,  58, 176,   4,  79,
        45,  59,  45, 109, 177,   6,   1,  12,  77, 178,  58,  6

In [299]:
Y.shape

(863,)

In [300]:
#we use the OHT
from tensorflow.keras.utils import to_categorical
Y=to_categorical(Y,num_classes=len(Tokenizer.word_index)+1)

In [301]:
Y

array([[0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [302]:
Y.shape

(863, 283)

In [303]:
#now we have X,Y then i build the Architecture of LSTM
#we first layer(embedding),2nd(LSTM),(dense_layer)..this main ARchtitecture
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding,LSTM,Dense

In [304]:
model=Sequential()

In [305]:
#Embedding(total_words,total_nos_of _dense_in_output_vector,which_setnse_have_maximum_length_in_the_given_data)

In [306]:
model.add(Embedding(len(Tokenizer.word_index)+1,100,input_length=57))

/usr/local/lib/python3.10/dist-packages/keras/src/layers/core/embedding.py:90: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [307]:
#we design a LSTM ...LSTM(NOs_of_nodes)
model.add(LSTM(150,return_sequences=False))

In [308]:
#we design dense....dense(totl_nos_of_word)
model.add(Dense(len(Tokenizer.word_index)+1,activation='softmax'))
#which word has highest probability his we assign the 1..example...p[0.2,0.5,0.6]..max(p)=0.6..then..result:-:[0,0,1]_in the same

In [309]:
#Now we do compile our model
#model.compile(loss='categorical_crossentropy',optimizer='adam',metrics=['accuracy'])
model.compile(loss='categorical_crossentropy',optimizer='adam',metrics=['accuracy'])

In [310]:
#Now we seen the summary of our model
model.summary()

Model: "sequential_7"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ embedding_9 (Embedding)              │ ?                           │     0 (unbuilt) │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ lstm_12 (LSTM)                       │ ?                           │     0 (unbuilt) │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_13 (Dense)                     │ ?                           │     0 (unbuilt) │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [311]:
model.fit(X,Y,epochs=10)

Epoch 1/10
27/27 ━━━━━━━━━━━━━━━━━━━━ 7s 106ms/step - accuracy: 0.0699 - loss: 5.5463
Epoch 2/10
27/27 ━━━━━━━━━━━━━━━━━━━━ 5s 103ms/step - accuracy: 0.0695 - loss: 5.0646
Epoch 3/10
27/27 ━━━━━━━━━━━━━━━━━━━━ 3s 105ms/step - accuracy: 0.0750 - loss: 4.9839
Epoch 4/10
27/27 ━━━━━━━━━━━━━━━━━━━━ 5s 101ms/step - accuracy: 0.0837 - loss: 5.0125
Epoch 5/10
27/27 ━━━━━━━━━━━━━━━━━━━━ 5s 103ms/step - accuracy: 0.0850 - loss: 4.8873
Epoch 6/10
27/27 ━━━━━━━━━━━━━━━━━━━━ 4s 146ms/step - accuracy: 0.0636 - loss: 4.8042
Epoch 7/10
27/27 ━━━━━━━━━━━━━━━━━━━━ 4s 136ms/step - accuracy: 0.0987 - loss: 4.6761
Epoch 8/10
27/27 ━━━━━━━━━━━━━━━━━━━━ 3s 102ms/step - accuracy: 0.1122 - loss: 4.5569
Epoch 9/10
27/27 ━━━━━━━━━━━━━━━━━━━━ 5s 99ms/step - accuracy: 0.1491 - loss: 4.3420
Epoch 10/10
27/27 ━━━━━━━━━━━━━━━━━━━━ 5s 100ms/step - accuracy: 0.1834 - loss: 4.1493


In [312]:
#Now we startb the prediction
#let's..Data1='mail'
#we take a tokenizer
#padding
#prediction

In [323]:
import time
n_test_data='data science'
for i in range(10):
    tokenizer1=Tokenizer.texts_to_sequences([n_test_data])[0]
    padding_=pad_sequences([tokenizer1],maxlen=57,padding='pre')
    #our model gives the probebility for multiple classes
    #then whic is highest probability then =1
    #now use argmax in numpy for tell us that higher probability which position
    import  numpy as np
    word_position=np.argmax(model.predict(padding_))
    for i,j in Tokenizer.word_index.items():
      if j==word_position:
        n_test_data=n_test_data+' '+i
        print(n_test_data)
        time.sleep(2)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step
data science is
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step
data science is the
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step
data science is the course
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step
data science is the course is
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step
data science is the course is the
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step
data science is the course is the course
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step
data science is the course is the course course
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 53ms/step
data science is the course is the course course is
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step
data science is the course is the course course is the
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step
data science is the course is the course course is the program


In [314]:
tokenizer1

[61, 7, 1, 12, 7]

In [315]:
padding_=pad_sequences([tokenizer1],maxlen=57,padding='pre')

In [316]:
padding_

array([[ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0, 61,  7,  1, 12,  7]], dtype=int32)

In [317]:
#Now send the padding_ in our model
model.predict(padding_)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step


array([[2.4160074e-05, 4.4056019e-01, 1.6241323e-02, 7.3088245e-03,
        1.9888368e-02, 3.5088044e-02, 2.7723633e-02, 2.2925818e-02,
        4.4097295e-03, 8.6299246e-03, 4.8808116e-03, 2.4372670e-03,
        1.3160712e-02, 9.0879668e-03, 4.9190149e-03, 4.0744529e-03,
        1.2840237e-02, 7.5609721e-03, 2.6947821e-03, 3.1468018e-03,
        6.6048773e-03, 5.5186870e-03, 5.6012785e-03, 3.6184236e-03,
        5.9242169e-03, 2.6129186e-03, 3.1330993e-03, 2.9155456e-03,
        3.9266529e-03, 4.8080385e-03, 5.6449702e-04, 3.4522105e-03,
        3.6482017e-03, 3.5303428e-03, 3.7127146e-03, 5.9864405e-03,
        2.0801839e-03, 2.9574498e-03, 6.3603562e-03, 2.6732057e-03,
        1.7501666e-03, 3.5414388e-03, 7.1685282e-03, 3.7463882e-03,
        5.6753065e-03, 1.3229328e-03, 6.5590176e-03, 4.3820147e-03,
        1.8778150e-05, 3.6706100e-03, 1.5855342e-03, 1.5066545e-03,
        3.7292121e-03, 3.3281005e-03, 3.0919188e-03, 1.5861951e-03,
        4.9129385e-03, 8.2439132e-04, 2.2483701e

In [318]:
#shape
model.predict(padding_).shape

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step


(1, 283)

In [319]:
#our model gives the probebility for multiple classes
#then whic is highest probability then =1
#now use argmax in numpy for tell us that higher probability which position
import  numpy as np
word_position=np.argmax(model.predict(padding_))
for i,j in Tokenizer.word_index.items():
  if j==word_position:
    print(i)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step
the
